DROP TABLE IF EXISTS user_info;

CREATE TABLE user_info
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	user_name VARCHAR(30) NOT NULL COMMENT '姓名',
	password VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
	salt VARCHAR(50) NULL DEFAULT NULL COMMENT '盐',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);