server:
  port: 8101
  servlet:
    context-path: /rabbitmq
spring:
  application:
    name: springboot2-rabbitmq
  rabbitmq:
    host: 192.168.1.160
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true  # 开启发送确认
    publisher-returns: true # 开启发送失败退回
    listener:
      direct:
        acknowledge-mode: manual  # 开启ACK
        retry:
          enabled: true #消费者端的重试
        prefetch: 1
      simple:
        retry:
          enabled: true #消费者端的重试
        acknowledge-mode: manual
        prefetch: 1

custom:
  rabbitmq:
    queue:
      direct: directQueue
      topic1: topicQueue1
      topic2: topicQueue2
      headers: headersQueue
    exchange:
      direct: directExchange
      topic: topicExchange
      header: headersExchange
    directRoutingKey: key.direct
    topicRoutingKey1: key.topic
    #其中路由键中*代表一个字符，#代表一个或多个字符
    topicRoutingKey2: key.#
    header: header_value


