server:
  port: 8103
  servlet:
    context-path: /redis-cluster
# Redis_config
#redis集群配置
spring:
  redis:
    cluster:
      nodes:
        - 10.211.55.6:7001
        - 10.211.55.6:7002
        - 10.211.55.6:7003
        - 10.211.55.6:7004
        - 10.211.55.6:7005
        - 10.211.55.6:7006
      max-redirects: 3
# Redis数据库索引（默认为0）
    database:  0
# Redis服务器连接密码（默认为空）
    password: 123456
# 连接超时时间（毫秒）
    timeout: 20000ms
#  springboot2.0后默认使用lettuce连接redis,底层使用的是netty框架做支撑
# 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 10
# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000ms
  # 连接池中的最大空闲连接
        max-idle:  5
  # 连接池中的最小空闲连接
        min-idle: 3
        time-between-eviction-runs: 5s